spring.application.name=Projeto_Final

# Configuração do Banco H2
spring.datasource.url=jdbc:h2:mem:rpgdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# Token isolado lido como texto pelo Service HTTP
mistral.token=ccxDy4bcJk0wcOqb3M0FMCG7HSg2dLQ3

spring.ai.mistralai.api-key=ccxDy4bcJk0wcOqb3M0FMCG7HSg2dLQ3